services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "8080:8080"
    volumes:
      - ./open-webui_data:/app/backend/data
    restart: always
    networks:
      server:
        ipv4_address: 172.31.0.2

networks:
  server:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
